name: lint
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Markdown Lint
        uses: avto-dev/markdown-lint@v1.5.0
      - name: Typos
        uses: crate-ci/typos@v1.19.0



